title: Bevestig weerstanden en jumperdraden aan een LED met soldeer en krimpkous
hero_image: afbeeldingen/banner.png
description: rgb-led-weerstand-soldeer-hitte-krimp beschrijving
version: 4
listed: false
copyedit: false
last_tested: "2022-01-28"
steps:
  - 
    title: Inleiding
