title: Attach resistors and jumper wires to an RGB LED with solder and heat shrink
hero_image: images/banner.png
description: rgb-led-resistor-solder-heat-shrink description
version: 4
listed: false
copyedit: false
last_tested: "2022-01-28"
steps:
  - 
    title: Introduction
