title: قم بتوصيل المقاومات وأسلاك التوصيل بمصباح RGB LED مع لحام وشرنك حراري (وهو عبارة عن أنبوب بلاستيكي يتقلص بالحرارة لحماية الاسلاك)
hero_image: images/banner.png
description: وصف متصل مضيء ملون-مقاومة-لحام-شرنك حراري (وهو عبارة عن أنبوب بلاستيكي يتقلص بالحرارة لحماية الاسلاك)
version: 4
listed: false
copyedit: false
last_tested: "2022-01-28"
steps:
  - 
    title: المقدمة
