---
title: Fixer des résistances et des fils de liaison à une LED RVB avec de la soudure et de la gaine thermorétractable
hero_image: images/banner.png
description: description led rvb-résistance-soudure-gaine-thermorétractable
version: 4
listed: false
copyedit: false
last_tested: "2022-01-28"
steps:
  - title: Introduction
